// SPDX-License-Identifier: GPL-3.0-or-later
// Packed 12-car reference-art sheet extracted from the approved Backyard Racer
// vehicle presentation. 12 rows, 512x160 each, front-left/rear-right.
inline constexpr IndexedAsset vehicle_photo_sheet_hd{512,1920,32,
#include "vehicle_photo_chunks/repl32_00.inc"
#include "vehicle_photo_chunks/repl32_01.inc"
#include "vehicle_photo_chunks/repl32_02.inc"
#include "vehicle_photo_chunks/repl32_03.inc"
#include "vehicle_photo_chunks/repl32_04.inc"
#include "vehicle_photo_chunks/repl32_05.inc"
#include "vehicle_photo_chunks/repl32_06.inc"
#include "vehicle_photo_chunks/repl32_07.inc"
#include "vehicle_photo_chunks/repl32_08.inc"
#include "vehicle_photo_chunks/repl32_09.inc"
#include "vehicle_photo_chunks/repl32_10.inc"
#include "vehicle_photo_chunks/repl32_11.inc"
#include "vehicle_photo_chunks/repl32_12.inc"
#include "vehicle_photo_chunks/repl32_13.inc"
#include "vehicle_photo_chunks/repl32_14.inc"
#include "vehicle_photo_chunks/repl32_15.inc"
};
